import * as THREE from './assets/three.module.min.js';
const host=document.querySelector('#scene'),visual=document.querySelector('.visual'),button=document.querySelector('#motion');
const reduced=matchMedia('(prefers-reduced-motion:reduce)'),mobile=matchMedia('(max-width:760px)');
let paused=reduced.matches,visible=true,renderer,frame=0,failed=false,progress=0,goal=0,phase=0,lastTime=0,previousStage=-1;
const captions=['La inteligencia empieza contigo.','Una intención toma forma.','El conocimiento encuentra conexiones.','El contexto se convierte en acción.'];
const labels=[['Tu voz','Tu contexto','Tus herramientas'],['Una intención','Una conversación','Un siguiente paso'],['Documentos','Memoria','Decisiones'],['Preparar','Revisar','Confirmar']];
function updateButton(){button.textContent=paused?'Activar movimiento':'Pausar movimiento';button.setAttribute('aria-pressed',String(paused))}
function fallback(){failed=true;cancelAnimationFrame(frame);document.body.classList.remove('has-webgl');document.querySelector('.fallback-note').hidden=false;button.hidden=true;host.querySelector('canvas')?.remove()}
updateButton();
try{
renderer=new THREE.WebGLRenderer({antialias:!mobile.matches,alpha:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,mobile.matches?1.3:1.7));renderer.setClearColor(0x070b14,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(37,1,.1,60);camera.position.set(0,0,8.8);const group=new THREE.Group();scene.add(group);
scene.add(new THREE.AmbientLight(0x9bbcff,2));const key=new THREE.DirectionalLight(0xe5faff,5);key.position.set(-3,4,5);scene.add(key);const fill=new THREE.PointLight(0x3583ff,50);fill.position.set(3,-2,3);scene.add(fill);const rim=new THREE.PointLight(0x47ddff,65);rim.position.set(-3,1,-2);scene.add(rim);
const material=new THREE.MeshPhysicalMaterial({color:0x4385ab,metalness:.62,roughness:.23,clearcoat:1,clearcoatRoughness:.17,emissive:0x102e58,emissiveIntensity:.6});
const sculpture=new THREE.Mesh(new THREE.TorusKnotGeometry(1.04,.22,mobile.matches?140:240,24,2,3),material);sculpture.rotation.set(.25,.1,.3);group.add(sculpture);
const core=new THREE.Mesh(new THREE.IcosahedronGeometry(.56,2),new THREE.MeshPhysicalMaterial({color:0x98e8ff,metalness:.35,roughness:.17,emissive:0x1a9bbc,emissiveIntensity:.45,clearcoat:1}));group.add(core);
const coreWire=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.IcosahedronGeometry(.67,1)),new THREE.LineBasicMaterial({color:0xd0faff,transparent:true,opacity:.5}));group.add(coreWire);
const rings=[];for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.87+i*.15,.013,8,128),new THREE.MeshBasicMaterial({color:i===1?0x8be7ff:0x346693,transparent:true,opacity:i===1?.8:.6}));ring.rotation.set(.7+i*.6,.35+i*.5,.2+i*.25);rings.push(ring);group.add(ring)}
const nodes=[];const nodeGeo=new THREE.SphereGeometry(.037,10,8);const nodeMat=new THREE.MeshBasicMaterial({color:0x96defb});for(let i=0;i<34;i++){const phi=Math.acos(1-2*(i+.5)/34),theta=Math.PI*(1+Math.sqrt(5))*i;const p=new THREE.Vector3(Math.cos(theta)*Math.sin(phi),Math.sin(theta)*Math.sin(phi),Math.cos(phi)).multiplyScalar(2.14);const node=new THREE.Mesh(nodeGeo,nodeMat);node.position.copy(p);nodes.push({mesh:node,base:p});group.add(node)}
const connectionPositions=[];for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){if(nodes[i].base.distanceTo(nodes[j].base)<1.32){connectionPositions.push(...nodes[i].base.toArray(),...nodes[j].base.toArray())}}const connectionGeo=new THREE.BufferGeometry();connectionGeo.setAttribute('position',new THREE.Float32BufferAttribute(connectionPositions,3));const connections=new THREE.LineSegments(connectionGeo,new THREE.LineBasicMaterial({color:0x39749b,transparent:true,opacity:.22}));group.add(connections);
const stars=[];let seed=43;function random(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646}for(let i=0;i<100;i++)stars.push((random()-.5)*11,(random()-.5)*11,(random()-.5)*5-3);const dustGeo=new THREE.BufferGeometry();dustGeo.setAttribute('position',new THREE.Float32BufferAttribute(stars,3));const dust=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0x5d8bae,size:.013,transparent:true,opacity:.55}));scene.add(dust);
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.position.z=camera.aspect<.85?10.4:8.7;camera.updateProjectionMatrix();requestFrame()}
const pointer={x:0,y:0};visual.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'||paused)return;const r=visual.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width-.5;pointer.y=(e.clientY-r.top)/r.height-.5;requestFrame()});visual.addEventListener('pointerleave',()=>{pointer.x=pointer.y=0});
function scroll(){if(mobile.matches){const r=visual.getBoundingClientRect();goal=THREE.MathUtils.clamp((innerHeight*.7-r.top)/(innerHeight*.7+r.height*.3),0,1)*3}else{const chapters=[...document.querySelectorAll('[data-stage]')];let target=0;chapters.forEach((el,i)=>{const r=el.getBoundingClientRect();if(r.top<innerHeight*.58)target=i+THREE.MathUtils.clamp((innerHeight*.38-r.top)/r.height,0,.98)});goal=Math.min(target,3)}requestFrame()}
function render(time){frame=0;if(failed||document.hidden||!visible)return;const delta=Math.min((time-lastTime)/1000||.016,.05);lastTime=time;if(!paused){phase+=delta*.16;progress+=(goal-progress)*Math.min(1,delta*5)}const spread=1+Math.sin(progress/3*Math.PI)*.25;group.rotation.y=phase+progress*1.18+pointer.x*.18;group.rotation.x=.1+Math.sin(phase*.4)*.1+progress*.24+pointer.y*.12;group.rotation.z=-.16+progress*.12;sculpture.rotation.y=progress*.6;sculpture.scale.setScalar(1-progress*.065);core.rotation.y=-phase*.7;coreWire.rotation.z=phase*.4;rings.forEach((r,i)=>{r.scale.setScalar(spread);r.rotation.z=.2+i*.25+phase*(i%2?-.2:.2)+progress*.2});nodes.forEach(n=>n.mesh.position.copy(n.base).multiplyScalar(spread));connections.scale.setScalar(spread);connections.material.opacity=.17+Math.sin(progress/3*Math.PI)*.23;group.position.y=Math.sin(phase)*.045;let stage=Math.round(progress);if(stage!==previousStage){previousStage=stage;document.querySelector('#scene-caption').textContent=captions[stage];document.querySelector('#scene-index').textContent=`0${stage+1} / 04`;['a','b','c'].forEach((id,i)=>document.querySelector('#label-'+id).textContent=labels[stage][i])}renderer.render(scene,camera);host.dataset.progress=progress.toFixed(2);host.dataset.frames=String(Number(host.dataset.frames||0)+1);if(!paused)requestFrame()}
function requestFrame(){if(!frame&&!failed&&!document.hidden&&visible)frame=requestAnimationFrame(render)}
button.addEventListener('click',()=>{paused=!paused;updateButton();requestFrame()});reduced.addEventListener('change',e=>{paused=e.matches;updateButton();requestFrame()});new ResizeObserver(resize).observe(host);const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible){lastTime=performance.now();requestFrame()}else{cancelAnimationFrame(frame);frame=0}},{rootMargin:'80px'});observer.observe(visual);addEventListener('scroll',scroll,{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(frame);frame=0}else{lastTime=performance.now();requestFrame()}});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();fallback()});document.body.classList.add('has-webgl');resize();scroll();
}catch(error){fallback()}
