const menu=document.querySelector('.menu'),nav=document.querySelector('#nav');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Cerrar':'Menú';nav.classList.toggle('open',open)});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='Menú'}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='Menú'}});
const destinations={playa:['Playa del Carmen','La ciudad y el mar, en tu día a día.','Una ubicación en el corazón de la Riviera Maya para quienes buscan combinar servicios, vida urbana y cercanía a la costa.'],tulum:['Tulum','Un espacio para reconectar.','Arquitectura, vegetación y un ritmo distinto. Explora un destino donde el diseño y el entorno natural forman parte de la experiencia.'],cancun:['Cancún','Una nueva mirada al horizonte.','Vida costera y conexión con el mundo. Consulta alternativas para disfrutar de un destino con servicios urbanos e infraestructura turística.']};
document.querySelectorAll('[data-destination]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-destination]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')});button.classList.add('active');button.setAttribute('aria-pressed','true');const [name,headline,copy]=destinations[button.dataset.destination];document.querySelector('#destination-label').textContent=name.toUpperCase();document.querySelector('#destination-headline').textContent=headline;document.querySelector('#destination-copy').textContent=copy;document.querySelector('#destination').value=name;}));
document.querySelector('#inquiry').addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.target),subject='Consulta inmobiliaria · '+form.get('destination');const body=`Hola, equipo Duke del Caribe.\n\nSoy ${form.get('name')}. Me interesa ${form.get('destination')} y estoy buscando: ${form.get('goal')}.\n\n${form.get('message')}\n\nQuisiera conocer las opciones y coordinar una asesoría.`;const link='mailto:contact@dukedelcaribe.com?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);document.querySelector('#form-status').textContent='Consulta preparada. Envíala desde tu aplicación de correo. Si no se abre, escribe a contact@dukedelcaribe.com.';window.location.href=link;});
const viewTexts={exterior:'Volúmenes abiertos, luz natural y una conexión directa con el entorno.',terrace:'Espacio exterior para compartir, descansar y disfrutar del paisaje.',overview:'Una perspectiva del conjunto: distribución, piscina y relación con el exterior.'};
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(n=>{n.classList.toggle('selected',n===b);n.setAttribute('aria-pressed',String(n===b))});document.querySelector('#view-description').textContent=viewTexts[b.dataset.view];window.dispatchEvent(new CustomEvent('scene-view',{detail:b.dataset.view}));}));
