import * as THREE from './assets/three.module.min.js';
const host=document.getElementById('scene'),pause=document.getElementById('pause'),hint=document.getElementById('scene-hint');
let paused=matchMedia('(prefers-reduced-motion: reduce)').matches,visible=true,frames=0;
try{
const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(0x101c24,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;host.appendChild(renderer.domElement);document.querySelector('.scene-fallback').classList.add('hidden');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,180);scene.fog=new THREE.Fog(0x101c24,34,70);scene.add(new THREE.HemisphereLight(0xd9e9ff,0x5c6858,2.7));
const sun=new THREE.DirectionalLight(0xffe1b3,4.2);sun.position.set(-7,16,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-14;sun.shadow.camera.right=14;sun.shadow.camera.top=14;sun.shadow.camera.bottom=-14;sun.shadow.normalBias=.035;scene.add(sun);const fill=new THREE.DirectionalLight(0x87c9eb,1.3);fill.position.set(8,6,-8);scene.add(fill);
const model=new THREE.Group();scene.add(model);const stone=new THREE.MeshStandardMaterial({color:0xd6d4c7,roughness:.8});const edge=new THREE.MeshStandardMaterial({color:0xf2ece0,roughness:.7});const wood=new THREE.MeshStandardMaterial({color:0x614432,roughness:.75});const dark=new THREE.MeshStandardMaterial({color:0x263438,roughness:.38});const glass=new THREE.MeshStandardMaterial({color:0x91b9bc,metalness:.65,roughness:.15,transparent:true,opacity:.65});const sand=new THREE.MeshStandardMaterial({color:0xb8b39c,roughness:1});const green=new THREE.MeshStandardMaterial({color:0x365d43,roughness:.8,side:THREE.DoubleSide});
function box(w,h,d,x,y,z,mat=stone,parent=model){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
// Architecture: cantilevered residence, open glazing, timber screens, shaded terraces.
box(14,.55,10,0,-.36,0,sand);box(10,.28,7,0,.02,0,edge);box(7.5,.18,4.1,-.25,2.65,-1.1,edge);box(7.8,.22,4.3,-.1,5.08,-1.1,edge);
box(7.1,2.45,.22,-.3,1.38,-2.98,stone);box(.22,2.45,4,-3.9,1.38,-1.05,stone);box(1.7,2.45,3.8,2.55,1.38,-1.1,stone);
box(6.8,2.1,.12,-.25,3.82,-2.9,stone);box(.18,2.1,3.8,-3.55,3.82,-1.08,stone);box(.18,2.1,3.8,3.05,3.82,-1.08,stone);
for(let i=0;i<6;i++){const x=-3.2+i*1.05;box(.055,2.2,.07,x,1.42,.7,dark);box(.98,2.05,.03,x+.49,1.42,.7,glass);box(.055,2.08,.07,x,3.9,.71,dark);box(.98,2.0,.03,x+.49,3.9,.71,glass);}
box(6.6,.04,3.4,-.25,2.79,-1.07,wood);box(6.6,.04,3.3,-.25,.2,-1.05,wood);
// Warm interior volumes visible through the glass.
const warm=new THREE.MeshStandardMaterial({color:0xe7c598,emissive:0xc98e43,emissiveIntensity:.25,roughness:.8});box(5.8,.07,.16,-.25,2.44,-1.8,warm);box(5.8,.07,.16,-.25,4.8,-1.8,warm);box(1.6,.42,.75,-1.8,.44,-.2,edge);box(.6,.32,.6,0,.4,-.6,wood);box(1.8,.38,1.25,.8,3.02,-1,edge);
// Timber vertical fins and pergola over the terrace.
for(let i=0;i<10;i++)box(.07,2.35,.34,1.75+i*.17,1.36,1.0,wood);box(.16,2.7,.16,4.3,1.5,2.6,wood);box(.16,2.7,.16,1.6,1.5,2.6,wood);for(let i=0;i<12;i++)box(2.9,.12,.1,2.9,2.86,.2+i*.22,wood);
// Pool set into the front deck.
box(6.5,.18,2.3,-1.35,.19,2.6,edge);const waterMat=new THREE.ShaderMaterial({uniforms:{time:{value:0}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec2 vUv;uniform float time;void main(){float wave=sin(vUv.x*60.+sin(vUv.y*25.+time)*2.)*.5+.5;float wave2=sin(vUv.y*70.-time*.5+sin(vUv.x*40.))*.5+.5;float light=pow(wave*wave2,5.);vec3 col=mix(vec3(.025,.25,.29),vec3(.18,.65,.69),vUv.y);gl_FragColor=vec4(col+light*.15,1.);}`});const pool=new THREE.Mesh(new THREE.PlaneGeometry(6.1,1.95),waterMat);pool.rotation.x=-Math.PI/2;pool.position.set(-1.35,.295,2.6);model.add(pool);
// Steps and glass railing.
for(let i=0;i<5;i++)box(2.1,.08,0.34,3.55,-.14+i*.07,4.5-i*.34,edge);box(6.7,.75,.035,-.25,3.12,1,glass);for(let x=-3.5;x<3.3;x+=1.1)box(.035,.85,.045,x,3.18,1,dark);
for(let x of [2.2,3.5]){box(.78,.16,1.25,x,.39,1.6,edge);box(.78,.48,.15,x,.6,1.02,edge);}
function palm(x,z,height){const g=new THREE.Group();g.position.set(x,0,z);model.add(g);const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(0,0,0),new THREE.Vector3(.15,height*.5,0),new THREE.Vector3(.5,height,0)]);const trunk=new THREE.Mesh(new THREE.TubeGeometry(curve,14,.085,6,false),wood);trunk.castShadow=true;g.add(trunk);for(let i=0;i<9;i++){const a=i*Math.PI*2/9,verts=[],indices=[];for(let j=0;j<10;j++){const t=j/9,r=t*2.15,y=height+Math.sin(t*Math.PI)*.65-t*.45,w=Math.sin(t*Math.PI)*.24;verts.push(.5+Math.cos(a)*r-Math.sin(a)*w,y,Math.sin(a)*r+Math.cos(a)*w,.5+Math.cos(a)*r+Math.sin(a)*w,y,Math.sin(a)*r-Math.cos(a)*w);if(j<9){const k=j*2;indices.push(k,k+1,k+2,k+1,k+3,k+2);}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geo.setIndex(indices);geo.computeVertexNormals();const leaf=new THREE.Mesh(geo,green);leaf.castShadow=true;g.add(leaf);}}
palm(-5,-2.8,5.0);palm(5.6,-2,4.5);palm(-5.5,2.2,3.8);
const bushGeo=new THREE.IcosahedronGeometry(.5,1);for(let i=0;i<15;i++){let b=new THREE.Mesh(bushGeo,green);b.position.set(-6.2+(i%8)*1.6,.22,i<8?-4.1:4.15);b.scale.set(1,.65,.6);model.add(b);}
const ocean=new THREE.Mesh(new THREE.PlaneGeometry(150,150),new THREE.MeshStandardMaterial({color:0x163d49,metalness:.35,roughness:.48,transparent:true,opacity:.55}));ocean.rotation.x=-Math.PI/2;ocean.position.y=-.67;scene.add(ocean);
let angle=.63,targetAngle=.63,elevation=10,targetElevation=10,dist=22,targetDist=22,scroll=0,drag=false,lastX=0,manual=false;
const views={exterior:[.63,10,22],terrace:[.15,6,20],overview:[.7,23,16]};function setView(view){[targetAngle,targetElevation,targetDist]=views[view]||views.exterior;manual=true;if(paused){angle=targetAngle;elevation=targetElevation;dist=targetDist;}render();}window.addEventListener('scene-view',e=>setView(e.detail));
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();render();}function render(){camera.position.set(Math.sin(angle)*dist*(camera.aspect<1?1.35:1),elevation*(camera.aspect<1?1.2:1),Math.cos(angle)*dist*(camera.aspect<1?1.35:1));camera.lookAt(0,1.4,0);renderer.render(scene,camera);frames++;window.__duke3d={frames,paused,angle,scroll,webgl:true};}
host.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;host.setPointerCapture(e.pointerId)});host.addEventListener('pointermove',e=>{if(!drag)return;targetAngle+=(e.clientX-lastX)*.008;lastX=e.clientX;manual=true;if(paused){angle=targetAngle;render();}});host.addEventListener('pointerup',()=>{drag=false});host.addEventListener('pointercancel',()=>{drag=false});
document.getElementById('rotate').addEventListener('click',()=>{targetAngle+=Math.PI/4;manual=true;if(paused){angle=targetAngle;render();}});document.getElementById('reset').addEventListener('click',()=>{[targetAngle,targetElevation,targetDist]=views.exterior;manual=false;if(paused){angle=targetAngle;elevation=targetElevation;dist=targetDist;render();}});
function updatePause(){pause.textContent=paused?'Activar movimiento':'Pausar';pause.setAttribute('aria-pressed',String(paused));render();}pause.addEventListener('click',()=>{paused=!paused;updatePause()});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{paused=e.matches;updatePause()});
window.addEventListener('scroll',()=>{scroll=Math.min(window.scrollY/900,1);if(!manual&&!paused)targetAngle=.63+scroll*.65},{passive:true});new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;},{rootMargin:'100px'}).observe(host);new ResizeObserver(resize).observe(host);let last=0;function tick(now){requestAnimationFrame(tick);if(!visible||document.hidden||now-last<33||paused)return;last=now;angle+=(targetAngle-angle)*.08;elevation+=(targetElevation-elevation)*.08;dist+=(targetDist-dist)*.08;waterMat.uniforms.time.value=now*.0007;render();}resize();updatePause();requestAnimationFrame(tick);hint.textContent='Arrastra para explorar';renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();document.querySelector('.scene-fallback').classList.remove('hidden');hint.textContent='Vista estática';});
}catch(error){hint.textContent='Vista estática disponible';document.querySelectorAll('.scene-controls button').forEach(b=>{b.hidden=true});window.__duke3d={webgl:false};}
